pipeline:
  s3:
    image: plugins/s3
    region: us-east-2
    bucket: drone-us-east-2-617683844790
    source: aws/Dockerrun.aws.json
    target: django-app-test/develop.json
    strip_prefix: aws/Dockerrun.aws.json
