pipeline:
  build:
    image: python:2.7
    commands:
      - pip install pep8
      - pep8 --ignore=E501 mysite
      - pip install awscli
      - aws ecr get-login --region us-east-2
      - aws sts get-caller-identity
      - export PASSWORD="`aws ecr get-login --region us-east-2 | sed 's/docker login -u AWS -p //;s_ -e none https://617683844790.dkr.ecr.us-east-2.amazonaws.com__'`"
      - export AWS_ACCESS_KEY_ID="`curl http://169.254.169.254/latest/meta-data/iam/security-credentials/DroneInstanceRole | grep AccessKeyId | awk -F '"' '{print $4}'`"
      - export AWS_SECRET_ACCESS_KEY="`curl http://169.254.169.254/latest/meta-data/iam/security-credentials/DroneInstanceRole |grep SecretAccessKey | awk -F '"' '{print $4}'`"
      - export
  s3:
    image: plugins/s3
    region: us-east-2
    access_key: $AWS_ACCESS_KEY_ID
    secret_key: $AWS_SECRET_ACCESS_KEY
    bucket: drone-us-east-2-617683844790
    source: aws/Dockerrun.aws.json
    target: django-app-test/develop.json
    strip_prefix: aws/Dockerrun.aws.json
  ecr:
    image: plugins/ecr
    access_key: $AWS_ACCESS_KEY_ID
    secret_key: $AWS_SECRET_ACCESS_KEY
    repo: 617683844790.dkr.ecr.us-east-2.amazonaws.com/django-app-test
    tags:
      - latest
      - 1.0.1
      - 1.0
